-- Auto-generated by scripts/exportChallengeSeed.mjs.
-- Source: src/data/challenges/*.js
USE bug_arena;

INSERT INTO challenges
  (id, slug, title, description, language, difficulty, bug_type, category,
   skills, tags, estimated_minutes, time_limit, base_score, hardening_bonus,
   xp_reward, version, function_name, starter_code, expected_behavior, hints,
   explanation, evaluation_tests)
VALUES
  (1001, 'the-broken-filter', 'The Broken Filter', 'Users disappear from the result after applying a case-insensitive search.', 'Python', 'Easy', 'logic', 'Logic', '["Filtering","Strings","Edge Cases"]', '["Python","Filtering","Logic"]', 8, 720, 350, 180, 100, 1, 'filter_users', 'def filter_users(users, query):
    return [
        user["name"] for user in users
        if query in user["name"]
    ]', 'Users disappear from the result after applying a case-insensitive search.', '["Read the expected behavior carefully.","Check the hidden edge cases after the core fix."]', 'The starter implementation contains a deliberate defect. The accepted solution must satisfy the complete challenge contract.', '[{"id":1,"name":"Basic filtering","type":"core","args":[[{"name":"Ali"},{"name":"Sara"},{"name":"Reza"}],"Ali"],"expected":["Ali"]},{"id":2,"name":"Case insensitive search","type":"core","args":[[{"name":"Ali"},{"name":"Sara"},{"name":"Reza"}],"ali"],"expected":["Ali"]},{"id":3,"name":"Empty query","type":"core","args":[[{"name":"Ali"},{"name":"Sara"},{"name":"Reza"}],""],"expected":["Ali","Sara","Reza"]},{"id":101,"name":"Mixed case search","type":"hidden","args":[[{"name":"Ali"},{"name":"ALIREZA"},{"name":"Sara"}],"aLi"],"expected":["Ali","ALIREZA"]},{"id":102,"name":"Whitespace query","type":"hidden","args":[[{"name":"Ali"},{"name":"Sara"}]," "],"expected":[]}]'),
  (1002, 'duplicate-signal', 'Duplicate Signal', 'A telemetry list should keep the first occurrence of each signal while preserving order.', 'Python', 'Easy', 'data-structure', 'Data Structures', '["Arrays","Deduplication","Order"]', '["Python","Arrays","Deduplication"]', 6, 600, 380, 190, 100, 1, 'unique_signals', 'def unique_signals(signals):
    return sorted(set(signals))', 'A telemetry list should keep the first occurrence of each signal while preserving order.', '["Read the expected behavior carefully.","Check the hidden edge cases after the core fix."]', 'The starter implementation contains a deliberate defect. The accepted solution must satisfy the complete challenge contract.', '[{"id":1,"name":"Remove duplicates","type":"core","args":[[1,2,2,3,1]],"expected":[1,2,3]},{"id":2,"name":"Preserve order","type":"core","args":[["b","a","b","c","a"]],"expected":["b","a","c"]},{"id":3,"name":"Empty list","type":"core","args":[[]],"expected":[]},{"id":101,"name":"Boolean values","type":"hidden","args":[[true,false,true,false]],"expected":[true,false]}]'),
  (1003, 'priority-inversion', 'Priority Inversion', 'Tasks must be ordered by priority, but tasks with the same priority must keep their original order.', 'Python', 'Medium', 'sorting', 'Algorithms', '["Sorting","Stability","Ordering"]', '["Python","Sorting","Stability"]', 10, 720, 520, 240, 100, 1, 'sort_tasks', 'def sort_tasks(tasks):
    return [
        task["name"]
        for task in sorted(tasks, key=lambda task: task["priority"])
    ]', 'Tasks must be ordered by priority, but tasks with the same priority must keep their original order.', '["Read the expected behavior carefully.","Check the hidden edge cases after the core fix."]', 'The starter implementation contains a deliberate defect. The accepted solution must satisfy the complete challenge contract.', '[{"id":1,"name":"Highest priority first","type":"core","args":[[{"name":"A","priority":1},{"name":"B","priority":3},{"name":"C","priority":2}]],"expected":["B","C","A"]},{"id":2,"name":"Stable ties","type":"core","args":[[{"name":"A","priority":2},{"name":"B","priority":2},{"name":"C","priority":1}]],"expected":["A","B","C"]},{"id":101,"name":"Negative priority","type":"hidden","args":[[{"name":"A","priority":-1},{"name":"B","priority":0},{"name":"C","priority":-3}]],"expected":["B","A","C"]}]'),
  (1004, 'windowed-average', 'Windowed Average', 'Calculate a moving average for each complete window of values.', 'Python', 'Medium', 'algorithm', 'Algorithms', '["Lists","Sliding Window","Statistics"]', '["Python","Lists","Algorithms"]', 12, 840, 560, 260, 100, 1, 'moving_average', 'def moving_average(values, window):
    return [
        sum(values[i:i + window]) / window
        for i in range(len(values) - window)
    ]', 'Calculate a moving average for each complete window of values.', '["Read the expected behavior carefully.","Check the hidden edge cases after the core fix."]', 'The starter implementation contains a deliberate defect. The accepted solution must satisfy the complete challenge contract.', '[{"id":1,"name":"Basic window","type":"core","args":[[1,2,3,4],2],"expected":[1.5,2.5,3.5]},{"id":2,"name":"Window of three","type":"core","args":[[2,4,6,8],3],"expected":[4,6]},{"id":101,"name":"Decimal values","type":"hidden","args":[[1,2,2,5],3],"expected":[1.6666666666666667,3]},{"id":102,"name":"Too-large window","type":"hidden","args":[[1,2],3],"expected":[]}]'),
  (1005, 'cache-key-collision', 'Cache Key Collision', 'Normalize a request path and query parameters into a deterministic cache key.', 'Python', 'Hard', 'normalization', 'Backend Logic', '["Strings","Normalization","Backend"]', '["Python","Strings","Normalization"]', 15, 900, 700, 320, 100, 1, 'cache_key', 'def cache_key(path, params):
    return path + ''?'' + ''&''.join(f''{k}={v}'' for k, v in params.items())', 'Normalize a request path and query parameters into a deterministic cache key.', '["Read the expected behavior carefully.","Check the hidden edge cases after the core fix."]', 'The starter implementation contains a deliberate defect. The accepted solution must satisfy the complete challenge contract.', '[{"id":1,"name":"Basic key","type":"core","args":["/Users",{"page":2,"sort":"name"}],"expected":"/users?page=2&sort=name"},{"id":2,"name":"Sorted parameters","type":"core","args":["/search",{"z":"9","a":"1"}],"expected":"/search?a=1&z=9"},{"id":101,"name":"Uppercase path","type":"hidden","args":["/API/Users/",{"q":"Ali"}],"expected":"/api/users?q=Ali"},{"id":102,"name":"Empty query","type":"hidden","args":["/health/",{}],"expected":"/health"}]'),
  (1006, 'boundary-window', 'Boundary Window', 'Calculate the maximum value inside each fixed-size window.', 'Python', 'Medium', 'logic', 'Algorithms', '["Arrays","Sliding Window"]', '["Python","Arrays","Sliding Window"]', 10, 780, 520, 240, 100, 1, 'max_windows', 'def max_windows(values, window):
    return [max(values[i:i + window]) for i in range(len(values) - window)]', 'Calculate the maximum value inside each fixed-size window.', '["Read the function contract carefully.","Check edge cases before changing the algorithm."]', 'The starter implementation violates the challenge contract. A correct solution must satisfy every core and hidden test.', '[{"id":1,"name":"Case 1","type":"core","args":[[1,3,2,5],2],"expected":[3,3,5]},{"id":2,"name":"Case 2","type":"core","args":[[4,1,7,2,6],3],"expected":[7,7,7]},{"id":3,"name":"Case 3","type":"hidden","args":[[1,2],3],"expected":[]},{"id":4,"name":"Case 4","type":"hidden","args":[[9,1,5],1],"expected":[9,1,5]}]'),
  (1007, 'quota-guard', 'Quota Guard', 'Return whether a request is allowed without exceeding the quota.', 'Python', 'Easy', 'logic', 'Backend Logic', '["Conditions","Backend"]', '["Python","Conditions","Backend"]', 6, 600, 350, 180, 100, 1, 'is_allowed', 'def is_allowed(used, quota, cost):
    return used + cost < quota', 'Return whether a request is allowed without exceeding the quota.', '["Read the function contract carefully.","Check edge cases before changing the algorithm."]', 'The starter implementation violates the challenge contract. A correct solution must satisfy every core and hidden test.', '[{"id":1,"name":"Case 1","type":"core","args":[8,10,2],"expected":true},{"id":2,"name":"Case 2","type":"core","args":[9,10,1],"expected":true},{"id":3,"name":"Case 3","type":"hidden","args":[10,10,1],"expected":false},{"id":4,"name":"Case 4","type":"hidden","args":[0,0,0],"expected":true}]'),
  (1008, 'casefold-index', 'Casefold Index', 'Find the first case-insensitive occurrence of a token in a list.', 'Python', 'Easy', 'logic', 'Logic', '["Strings","Search"]', '["Python","Strings","Search"]', 6, 600, 350, 180, 100, 1, 'find_token', 'def find_token(items, token):
    token = token.lower()
    for index, item in enumerate(items):
        if item == token:
            return index
    return -1', 'Find the first case-insensitive occurrence of a token in a list.', '["Read the function contract carefully.","Check edge cases before changing the algorithm."]', 'The starter implementation violates the challenge contract. A correct solution must satisfy every core and hidden test.', '[{"id":1,"name":"Case 1","type":"core","args":[["Alpha","Beta","GAMMA"],"gamma"],"expected":2},{"id":2,"name":"Case 2","type":"core","args":[["A","b","C"],"x"],"expected":-1},{"id":3,"name":"Case 3","type":"hidden","args":[["Node","node"],"NODE"],"expected":0},{"id":4,"name":"Case 4","type":"hidden","args":[["Test"],"TEST"],"expected":0}]'),
  (1009, 'merge-intervals', 'Merge Intervals', 'Merge overlapping numeric intervals into a compact ordered list.', 'Python', 'Hard', 'logic', 'Algorithms', '["Intervals","Sorting"]', '["Python","Intervals","Sorting"]', 15, 900, 700, 320, 100, 1, 'merge_intervals', 'def merge_intervals(intervals):
    intervals = sorted(intervals)
    merged = []
    for start, end in intervals:
        if not merged or start >= merged[-1][1]:
            merged.append([start, end])
        else:
            merged[-1][1] = max(merged[-1][1], end)
    return merged', 'Merge overlapping numeric intervals into a compact ordered list.', '["Read the function contract carefully.","Check edge cases before changing the algorithm."]', 'The starter implementation violates the challenge contract. A correct solution must satisfy every core and hidden test.', '[{"id":1,"name":"Case 1","type":"core","args":[[[1,3],[2,6],[8,10]]],"expected":[[1,6],[8,10]]},{"id":2,"name":"Case 2","type":"core","args":[[[1,4],[4,5]]],"expected":[[1,5]]},{"id":3,"name":"Case 3","type":"hidden","args":[[[5,7],[1,2],[2,4]]],"expected":[[1,4],[5,7]]},{"id":4,"name":"Case 4","type":"hidden","args":[[]],"expected":[]}]'),
  (1010, 'frequency-rank', 'Frequency Rank', 'Return the most frequent values, breaking ties by first appearance.', 'Python', 'Medium', 'logic', 'Data Structures', '["Hash Map","Counting"]', '["Python","Hash Map","Counting"]', 10, 780, 520, 240, 100, 1, 'frequency_rank', 'def frequency_rank(values, limit):
    counts = {}
    order = {}
    for index, value in enumerate(values):
        counts[value] = counts.get(value, 0) + 1
        order.setdefault(value, index)
    ranked = sorted(counts, key=lambda value: (-counts[value], value))
    return ranked[:limit]', 'Return the most frequent values, breaking ties by first appearance.', '["Read the function contract carefully.","Check edge cases before changing the algorithm."]', 'The starter implementation violates the challenge contract. A correct solution must satisfy every core and hidden test.', '[{"id":1,"name":"Case 1","type":"core","args":[[3,1,3,2,1,3],2],"expected":[3,1]},{"id":2,"name":"Case 2","type":"core","args":[["b","a","a","b"],2],"expected":["b","a"]},{"id":3,"name":"Case 3","type":"hidden","args":[[1,2,3],5],"expected":[1,2,3]},{"id":4,"name":"Case 4","type":"hidden","args":[[],3],"expected":[]}]'),
  (1011, 'parse-version', 'Version Parser', 'Compare semantic version strings and return the larger version.', 'Python', 'Medium', 'logic', 'Backend Logic', '["Parsing","Strings"]', '["Python","Parsing","Strings"]', 10, 780, 520, 240, 100, 1, 'max_version', 'def max_version(a, b):
    def parts(value):
        return tuple(int(x) for x in value.split(''.''))
    return a if parts(a) > parts(b) else b', 'Compare semantic version strings and return the larger version.', '["Read the function contract carefully.","Check edge cases before changing the algorithm."]', 'The starter implementation violates the challenge contract. A correct solution must satisfy every core and hidden test.', '[{"id":1,"name":"Case 1","type":"core","args":["1.2.10","1.2.9"],"expected":"1.2.10"},{"id":2,"name":"Case 2","type":"core","args":["2.0","2.0.0"],"expected":"2.0"},{"id":3,"name":"Case 3","type":"hidden","args":["1.4.0","1.4.1"],"expected":"1.4.1"},{"id":4,"name":"Case 4","type":"hidden","args":["1.0.0","1.0.0"],"expected":"1.0.0"}]'),
  (1012, 'balanced-brackets', 'Balanced Brackets', 'Check whether brackets are correctly nested and closed.', 'Python', 'Medium', 'logic', 'Parsing', '["Stack","Validation"]', '["Python","Stack","Validation"]', 10, 780, 520, 240, 100, 1, 'is_balanced', 'def is_balanced(text):
    return sum(text.count(char) for char in ''([{'') == sum(text.count(char) for char in '')]}'')', 'Check whether brackets are correctly nested and closed.', '["Read the function contract carefully.","Check edge cases before changing the algorithm."]', 'The starter implementation violates the challenge contract. A correct solution must satisfy every core and hidden test.', '[{"id":1,"name":"Case 1","type":"core","args":["([])"],"expected":true},{"id":2,"name":"Case 2","type":"core","args":["([)]"],"expected":false},{"id":3,"name":"Case 3","type":"hidden","args":["hello {world}"],"expected":true},{"id":4,"name":"Case 4","type":"hidden","args":["((("],"expected":false}]'),
  (1013, 'normalize-email', 'Email Normalizer', 'Normalize an email address for duplicate-account detection.', 'Python', 'Easy', 'logic', 'Data Cleaning', '["Strings","Normalization"]', '["Python","Strings","Normalization"]', 6, 600, 350, 180, 100, 1, 'normalize_email', 'def normalize_email(email):
    local, domain = email.strip().split(''@'', 1)
    return local + ''@'' + domain.lower()', 'Normalize an email address for duplicate-account detection.', '["Read the function contract carefully.","Check edge cases before changing the algorithm."]', 'The starter implementation violates the challenge contract. A correct solution must satisfy every core and hidden test.', '[{"id":1,"name":"Case 1","type":"core","args":[" Alice@Example.COM "],"expected":"alice@example.com"},{"id":2,"name":"Case 2","type":"core","args":["BOB@MAIL.com"],"expected":"bob@mail.com"},{"id":3,"name":"Case 3","type":"hidden","args":["Carol@Example.org"],"expected":"carol@example.org"},{"id":4,"name":"Case 4","type":"hidden","args":[" dave@EXAMPLE.ORG "],"expected":"dave@example.org"}]'),
  (1014, 'rolling-errors', 'Rolling Error Rate', 'Calculate error rate for each complete window of request outcomes.', 'Python', 'Hard', 'logic', 'Telemetry', '["Statistics","Sliding Window"]', '["Python","Statistics","Sliding Window"]', 15, 900, 700, 320, 100, 1, 'error_rates', 'def error_rates(outcomes, window):
    return [sum(outcomes[i:i + window]) / window for i in range(len(outcomes) - window)]', 'Calculate error rate for each complete window of request outcomes.', '["Read the function contract carefully.","Check edge cases before changing the algorithm."]', 'The starter implementation violates the challenge contract. A correct solution must satisfy every core and hidden test.', '[{"id":1,"name":"Case 1","type":"core","args":[[1,0,1,1],2],"expected":[0.5,0.5,1]},{"id":2,"name":"Case 2","type":"core","args":[[0,0,1,0,1],3],"expected":[0.3333333333333333,0.3333333333333333,0.6666666666666666]},{"id":3,"name":"Case 3","type":"hidden","args":[[0,0],3],"expected":[]},{"id":4,"name":"Case 4","type":"hidden","args":[[1,1,0],1],"expected":[1,1,0]}]'),
  (1015, 'priority-queue', 'Priority Queue Fix', 'Process jobs by highest priority while preserving arrival order for ties.', 'Python', 'Hard', 'logic', 'Data Structures', '["Sorting","Stability"]', '["Python","Sorting","Stability"]', 15, 900, 700, 320, 100, 1, 'process_jobs', 'def process_jobs(jobs):
    return [job[''id''] for job in sorted(jobs, key=lambda job: job[''priority''])]', 'Process jobs by highest priority while preserving arrival order for ties.', '["Read the function contract carefully.","Check edge cases before changing the algorithm."]', 'The starter implementation violates the challenge contract. A correct solution must satisfy every core and hidden test.', '[{"id":1,"name":"Case 1","type":"core","args":[[{"id":"A","priority":1},{"id":"B","priority":3},{"id":"C","priority":3}]],"expected":["B","C","A"]},{"id":2,"name":"Case 2","type":"core","args":[[{"id":"x","priority":0},{"id":"y","priority":-1}]],"expected":["x","y"]},{"id":3,"name":"Case 3","type":"hidden","args":[[]],"expected":[]},{"id":4,"name":"Case 4","type":"hidden","args":[[{"id":"first","priority":5},{"id":"second","priority":5}]],"expected":["first","second"]}]')
ON DUPLICATE KEY UPDATE
  slug = VALUES(slug), title = VALUES(title), description = VALUES(description),
  language = VALUES(language), difficulty = VALUES(difficulty), bug_type = VALUES(bug_type),
  category = VALUES(category), skills = VALUES(skills), tags = VALUES(tags),
  estimated_minutes = VALUES(estimated_minutes), time_limit = VALUES(time_limit),
  base_score = VALUES(base_score), hardening_bonus = VALUES(hardening_bonus),
  xp_reward = VALUES(xp_reward), version = VALUES(version),
  function_name = VALUES(function_name), starter_code = VALUES(starter_code),
  expected_behavior = VALUES(expected_behavior), hints = VALUES(hints),
  explanation = VALUES(explanation), evaluation_tests = VALUES(evaluation_tests),
  is_active = 1;

INSERT INTO challenge_tests (challenge_id, test_index, name, test_type, is_hidden)
VALUES
  (1001, 0, 'Basic filtering', 'core', 0),
  (1001, 1, 'Case insensitive search', 'core', 0),
  (1001, 2, 'Empty query', 'core', 0),
  (1001, 3, 'Mixed case search', 'hidden', 1),
  (1001, 4, 'Whitespace query', 'hidden', 1),
  (1002, 0, 'Remove duplicates', 'core', 0),
  (1002, 1, 'Preserve order', 'core', 0),
  (1002, 2, 'Empty list', 'core', 0),
  (1002, 3, 'Boolean values', 'hidden', 1),
  (1003, 0, 'Highest priority first', 'core', 0),
  (1003, 1, 'Stable ties', 'core', 0),
  (1003, 2, 'Negative priority', 'hidden', 1),
  (1004, 0, 'Basic window', 'core', 0),
  (1004, 1, 'Window of three', 'core', 0),
  (1004, 2, 'Decimal values', 'hidden', 1),
  (1004, 3, 'Too-large window', 'hidden', 1),
  (1005, 0, 'Basic key', 'core', 0),
  (1005, 1, 'Sorted parameters', 'core', 0),
  (1005, 2, 'Uppercase path', 'hidden', 1),
  (1005, 3, 'Empty query', 'hidden', 1),
  (1006, 0, 'Case 1', 'core', 0),
  (1006, 1, 'Case 2', 'core', 0),
  (1006, 2, 'Case 3', 'hidden', 1),
  (1006, 3, 'Case 4', 'hidden', 1),
  (1007, 0, 'Case 1', 'core', 0),
  (1007, 1, 'Case 2', 'core', 0),
  (1007, 2, 'Case 3', 'hidden', 1),
  (1007, 3, 'Case 4', 'hidden', 1),
  (1008, 0, 'Case 1', 'core', 0),
  (1008, 1, 'Case 2', 'core', 0),
  (1008, 2, 'Case 3', 'hidden', 1),
  (1008, 3, 'Case 4', 'hidden', 1),
  (1009, 0, 'Case 1', 'core', 0),
  (1009, 1, 'Case 2', 'core', 0),
  (1009, 2, 'Case 3', 'hidden', 1),
  (1009, 3, 'Case 4', 'hidden', 1),
  (1010, 0, 'Case 1', 'core', 0),
  (1010, 1, 'Case 2', 'core', 0),
  (1010, 2, 'Case 3', 'hidden', 1),
  (1010, 3, 'Case 4', 'hidden', 1),
  (1011, 0, 'Case 1', 'core', 0),
  (1011, 1, 'Case 2', 'core', 0),
  (1011, 2, 'Case 3', 'hidden', 1),
  (1011, 3, 'Case 4', 'hidden', 1),
  (1012, 0, 'Case 1', 'core', 0),
  (1012, 1, 'Case 2', 'core', 0),
  (1012, 2, 'Case 3', 'hidden', 1),
  (1012, 3, 'Case 4', 'hidden', 1),
  (1013, 0, 'Case 1', 'core', 0),
  (1013, 1, 'Case 2', 'core', 0),
  (1013, 2, 'Case 3', 'hidden', 1),
  (1013, 3, 'Case 4', 'hidden', 1),
  (1014, 0, 'Case 1', 'core', 0),
  (1014, 1, 'Case 2', 'core', 0),
  (1014, 2, 'Case 3', 'hidden', 1),
  (1014, 3, 'Case 4', 'hidden', 1),
  (1015, 0, 'Case 1', 'core', 0),
  (1015, 1, 'Case 2', 'core', 0),
  (1015, 2, 'Case 3', 'hidden', 1),
  (1015, 3, 'Case 4', 'hidden', 1)
ON DUPLICATE KEY UPDATE
  name = VALUES(name), test_type = VALUES(test_type), is_hidden = VALUES(is_hidden);
