// Export the full challenge registry to MySQL seed SQL.
// The browser bundle remains an offline fallback, but MySQL owns published metadata/content.
import { writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { allChallenges } from '../src/data/challenges/index.js'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const q = (value) => `'${String(value ?? '').replace(/\\/g, '\\\\').replace(/'/g, "''")}'`
const json = (value) => `CAST(${q(JSON.stringify(value ?? []))} AS JSON)`

const rows = allChallenges.map((c) => [
  c.id, q(c.slug), q(c.title), q(c.description), q(c.language || 'Python'),
  q(c.difficulty), q(c.bugType || 'logic'), q(c.category || 'Logic'),
  json(c.skills), json(c.tags), c.estimatedTime, c.timeLimit, c.baseScore,
  c.hardeningBonus, 100, c.version, q(c.evaluation?.functionName || ''),
  q(c.code || ''), q(c.description || ''), json(c.hints), q(c.explanation || ''),
  json(c.evaluation?.tests || []),
])

const challengeLines = rows.map((r) => `  (${r.join(', ')})`)
const testLines = allChallenges.flatMap((c) =>
  (c.evaluation?.tests || []).map((test, index) =>
    `  (${c.id}, ${index}, ${q(test.name)}, ${q(test.type)}, ${test.type === 'hidden' ? 1 : 0})`
  )
)

const sql = `-- Auto-generated by scripts/exportChallengeSeed.mjs.
-- Source: src/data/challenges/*.js
USE bug_arena;

INSERT INTO challenges
  (id, slug, title, description, language, difficulty, bug_type, category,
   skills, tags, estimated_minutes, time_limit, base_score, hardening_bonus,
   xp_reward, version, function_name, starter_code, expected_behavior, hints,
   explanation, evaluation_tests)
VALUES
${challengeLines.join(',\n')}
AS new
ON DUPLICATE KEY UPDATE
  slug = new.slug, title = new.title, description = new.description,
  language = new.language, difficulty = new.difficulty, bug_type = new.bug_type,
  category = new.category, skills = new.skills, tags = new.tags,
  estimated_minutes = new.estimated_minutes, time_limit = new.time_limit,
  base_score = new.base_score, hardening_bonus = new.hardening_bonus,
  xp_reward = new.xp_reward, version = new.version,
  function_name = new.function_name, starter_code = new.starter_code,
  expected_behavior = new.expected_behavior, hints = new.hints,
  explanation = new.explanation, evaluation_tests = new.evaluation_tests,
  is_active = 1;

INSERT INTO challenge_tests (challenge_id, test_index, name, test_type, is_hidden)
VALUES
${testLines.join(',\n')}
AS new
ON DUPLICATE KEY UPDATE
  name = new.name, test_type = new.test_type, is_hidden = new.is_hidden;
`
writeFileSync(join(root, 'backend/database/seed_challenges.sql'), sql)
console.log(`Exported ${allChallenges.length} challenges, ${testLines.length} tests.`)
